# Site settings
title: Bens-Autoramas
email: bensautoramas@gmail.com
description: Write an awesome description for your new site here.
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
# Build settings
